---
name: build-test-deploy
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: "g++ ./quadratic_solver.cpp -o quadratic_solver.exe"
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: "bash quadratic.sh"
   
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: "chmod ugo+x quadratic_solver.exe" 
      - run: "./quadratic_solver.exe 1 2 1"
