---
name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checout repo
        uses: actions/checkout@v3
      - run: "G++ ./quadratic_solver.cpp -o quadratic_solver.exe"
